### PR TITLE
feat(tree-sitter): Add support for Java 22

### PR DESCRIPTION
**Pull request by devsprint**

### CODE REVIEW

**Comment by tinco** [comment]
Very cool! I suppose we don't have any tests for the refs/defs module.

**Comment by devsprint** [comment]
I have added a basic test in `outliner.rs`.  The linter reported issue I guess that it should be fixed into a separate PR.

**Comment by timonv** [comment]
Nice! Currently all tree-sitter languages are exposed via the tree-sitter feature flag in `swiftide/swiftide`, could you add it there as well?

> Very cool! I suppose we don't have any tests for the refs/defs module.
Indeed, only a very basic one is present in the transformer. That is very odd, I recall writing them for each language 🤔 Would be greatly appreciated if at least a simple test for refs and defs is added there.

I'll fix the linting issue tomorrow.

**Review by timonv — CHANGES_REQUESTED** [review]
Nice! Currently all tree-sitter languages are exposed via the tree-sitter feature flag in swiftide/swiftide, could you add it there as well?

> Very cool! I suppose we don't have any tests for the refs/defs module.
Indeed, only a very basic one is present in the transformer. That is very odd, I recall writing them for each language 🤔 Would be greatly appreciated if at least a simple test for refs and defs is added there.

I'll fix the linting issue tomorrow.

**Comment by timonv** [comment]
> Nice! Currently all tree-sitter languages are exposed via the tree-sitter feature flag in swiftide/swiftide, could you add it there as well?

It's late, it's a single feature flag, my bad

**Comment by timonv** [comment]
Master should be fixed! I've updated the branch

**Pull request merged**
