### PR TITLE
refactor: Improve builder api with `bon`

### PR DESCRIPTION
**Pull request by timonv**

### CODE REVIEW

**Comment by timonv** [comment]
It's a cool idea, but the library is not there yet, lacking building customization. Next release probably has more with custom setters, but still missing more. Perhaps check it out again in a couple of months or so.

**Comment by Veetaha** [comment]
Hi @timonv, could share what you'd like to see in `bon` that's missing now? As I understand it's the customization of setters, which is indeed comming in the next release, but what is "still missing more"?

**Comment by Veetaha** [comment]
I see, there is an example of how to add methods to the builder directly in this PR description https://github.com/elastio/bon/pull/145. The documentation for this feature is not ready at the moment, but it's soon to be released

**Comment by timonv** [comment]
@Veetaha Thanks! That looks really good, I'll give it another try soon. Out of curiosity, how did you find this PR? I'd love to do the same for this repository.

**Comment by Veetaha** [comment]
Through the github search with todays date/prev week range:
```
bon created:2024-11-04 language:Rust
```
image

There is also a [dependency graph](https://github.com/elastio/bon/network/dependents) with reverse dependencies.

**Comment by timonv** [comment]
What a great idea, thanks for being so proactive <3

**Pull request closed without merging**
